export enum AuthActionTypes {
    SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR = 'SIGN_UP_ERROR',
    LOG_IN_REQUEST = 'LOGIN_REQUEST',
    LOG_IN_SUCCESS = 'LOGIN_SUCCESS',
    LOG_IN_ERROR = 'LOGIN_ERROR',
    LOG_OUT_REQUEST ='LOG_OUT_REQUEST',
    LOG_OUT_SUCCESS ='LOG_OUT_SUCCESS',
    LOG_OUT_ERROR ='LOG_OUT_ERROR',
    RESTORE_TOKEN_REQUEST = 'RESTORE_TOKEN_REQUEST',
    RESTORE_TOKEN_SUCCESS = 'RESTORE_TOKEN_SUCCESS',
    RESTORE_TOKEN_ERROR = 'RESTORE_TOKEN_ERROR'
};

export enum AuthActionTypesToolkit {
    SIGN_UP = 'SIGN_UP',
    LOG_IN = 'LOGIN',
    LOG_OUT ='LOG_OUT',
    RESTORE_TOKEN = 'RESTORE_TOKEN',

};